BBBB BBBBBB
XXXXXXXXX XXXXX
XXXXXX
    XXXXXX
        XXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBX XX
    XXXXXXX
    XXXXXX
    
XXXXXXXX XX XXXXXXXXX
XXXXX XXXXXXXXXXXXXX
  BBBBBBBBBB
  BBB BBBBB BB BBBB
    XXX
      XXXX
      
      BB BBBBBBBBBBBBBBB
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
      BBBBB
      BBB BBBBB BB BBBBBBBBBBBB
        XX XXXXXXXXXXXXX XXXXXXXXX
      BBBBBB
    XXXX
  BBBBBB
  XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
XXXXXXX

