BBBBBBB BBBBBBBBBBB

    BBBB BBBB
    BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
    
BBBBB BBBB

   BB BBBBBBBBBBB
  XXXXXXX XXXXXXXX XXX XXXXXXXX XXXXXX XXXXXX XXXXXX XXX XXXXXXXXXX
BBBBB

BB BBBB
  BB BBBBBBBBBBBBBBBBBBBBB
    XXXXXXX XXXXXXX XXXXXXX XXXX XXXXXX XX XXXX XXXXX XX XXXXXXXX
    XXXXXX XXXXX XXXX XX XXXXXXX XXXX XXX XXXXXXXXXXX
  BBBB
    XXX gettext(u'login_title') XXXXX
  BBBBB
BBBBB

XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBXX
BBBBBBBBBB
XXXXXXX

XXXX
  XXXX gettext(u'login_name') XXXXX
  XXXXXXXXX
XXXXX

XXXX
  XXXX gettext(u'login_password') XXXXX
  XXXXXXXXX
XXXXX
XXXXXXXX
XXXX
XXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'log_in') X XX
XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XX
XXXXXXX


XXXXX XXXXXXBBB BBBBBBBBBBBBBBBBXXXXXXXX XXXXXXXXXXXXXXX

BBBBBBBB
